### Theoretical Question

### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations



Purpose of Numpy:
Numeric calculation
Efficient Array

Advantages of Numpy:
fast calculation
ease of use 
memory efficiency

NumPy indeed provides a powerful N-dimensional array object (numpy.ndarray) that enhances Python's capabilities for numerical operations and scientific computing. 

### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [ ]:
np.mean() and np.average() both functions are used to find average of array but when we have to find weighted average of any array we use np.average 

### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays

In [45]:
import numpy as np
a=np.array([1,2,3])
b=np.flip(a)

In [46]:
b             # for one dimensional

array([3, 2, 1])

In [43]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])  # for 2-D 
b=np.flip(a)

In [44]:
b

array([[6, 5, 4],
       [3, 2, 1]])

### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

In [ ]:
We can determine the data type of elements by using "dtype" attributes. It plays important role in memory manage, as different data type consumes 
different amount of memory so by by choosing appropriate data type we can save memory ,it also affects computational performance if data types are small
then it consumes less memory and give fast result in contrast if there is large data type it consume more space and take time in computing value

### .5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python list

In [ ]:
ndarray: ndarray are Ndimensional homogeneous data container used for numeric computation in python
Key features of ndarray : Homogeneous data type ,multidimensional
python list doesn't provide multi dimensional support as nd array and it is heterogeneous data container


### 6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

In [ ]:
NumPy arrays provide vectorised operation and efficient memory access whereas python list require explicit
iteration operation and consumes more memory in comparision to NumPy arrays . 

### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

In [28]:
arr=np.array([[2,3,4],[5,6,7]])

In [32]:
np.vstack(arr) #it joins two or mpre array vertically

array([[2, 3, 4],
       [5, 6, 7]])

In [33]:
np.hstack(arr)  #it joins two or more rows horizontally

array([2, 3, 4, 5, 6, 7])

### 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions

In [34]:
a=np.array([[2,3,4],[4,5,6]])  #it flip the array from left to right vertically
np.fliplr(a)

array([[4, 3, 2],
       [6, 5, 4]])

In [36]:
a=np.array([[2,3,4],[4,5,6]])   #it flip the array from up to down horizontally
np.flipud(a)

array([[4, 5, 6],
       [2, 3, 4]])

### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [46]:
a= np.array([[2,3,4],[4,5,6,],[4,3,6],[6,7,8]])
b=np.array_split(a,2,axis=1)  #uneven splits go into last sub-array
b

[array([[2, 3],
        [4, 5],
        [4, 3],
        [6, 7]]),
 array([[4],
        [6],
        [6],
        [8]])]

### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations

In [ ]:
vectorisation means performing operations on entire arrays at once. 
It is efficient because it process multiple element simultaneously
it saves our time by doing fast calculation

broadcasting allow us to performe operation on different shapes of array 
when dimension are not same it stretches the smaller shape to match with broader one

In [7]:
import numpy as np
arr=np.array([1, 2, 3])
arr1=np.array([5])
arr+arr1


array([6, 7, 8])

## Practical Questions:

** 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [3]:
import numpy as np
import random
arr=np.random.randint(1,100,(3,3,) , dtype= int)

In [4]:
arr


array([[64, 41, 44],
       [62, 34, 88],
       [72, 22, 51]], dtype=int32)

In [9]:
arr.T #interchanged

array([[64, 62, 72],
       [41, 34, 22],
       [44, 88, 51]], dtype=int32)

**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [47]:
arr1= np.arange(10)

In [48]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [15]:
import random
import numpy as np
arr= np.random.rand(4, 4) 

In [16]:
arr

array([[0.03012628, 0.70515506, 0.41555221, 0.6717597 ],
       [0.60696417, 0.59396851, 0.68897488, 0.50482212],
       [0.81481484, 0.85118711, 0.84634631, 0.98491317],
       [0.16247235, 0.55080482, 0.66750422, 0.61240672]])

In [17]:
border_array = np.zeros((6, 6))

In [18]:
border_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
border_array[1:5, 1:5]=arr

In [22]:
border_array

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.03012628, 0.70515506, 0.41555221, 0.6717597 ,
        0.        ],
       [0.        , 0.60696417, 0.59396851, 0.68897488, 0.50482212,
        0.        ],
       [0.        , 0.81481484, 0.85118711, 0.84634631, 0.98491317,
        0.        ],
       [0.        , 0.16247235, 0.55080482, 0.66750422, 0.61240672,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [3]:
arr= np.linspace(10,60,5)
arr

array([10. , 22.5, 35. , 47.5, 60. ])

### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element

In [4]:
a= ["python", "numpy", "pandas"]
arr=np.array([(i).upper() for i in a])

In [5]:
arr

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [6]:
a= ["python", "numpy", "pandas"]
arr=np.array([(i).lower() for i in a])
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [12]:
a =["python", "numpy", "pandas"]
arr1=np.array([(i).title() for i in a])

In [13]:
arr1

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [50]:
import numpy as np
my_words = np.array ("hello, mumbai , banglore")
s= np.char.join("  ",my_words)
s

array('h  e  l  l  o  ,     m  u  m  b  a  i     ,     b  a  n  g  l  o  r  e',
      dtype='<U70')

### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [13]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,6,5],[2,4,2]])
arr1+arr2


array([[8, 8, 8],
       [6, 9, 8]])

In [14]:
arr1-arr2


array([[-6, -4, -2],
       [ 2,  1,  4]])

In [15]:
arr1*arr2

array([[ 7, 12, 15],
       [ 8, 20, 12]])

In [16]:
arr1/arr2

array([[0.14285714, 0.33333333, 0.6       ],
       [2.        , 1.25      , 3.        ]])

### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [17]:
arr=np.eye(5)

In [18]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.diag(arr)

array([1., 1., 1., 1., 1.])

### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array

In [10]:
import random
a=np.random.randint(0,1000,100)

In [11]:
a

array([512, 764, 474, 830, 499, 543, 620, 374, 357, 418, 918, 285,  23,
       986, 320, 189, 992,  68, 353,  63, 367, 948, 792, 597, 465, 119,
       259, 800, 988,  93, 286, 831,   2, 275, 190, 480, 654, 401, 664,
       270,  78,  74, 611, 286, 306, 497, 408, 370, 993,  62, 180, 731,
       850, 312, 190, 615, 565,  71, 378, 641, 113, 116, 711, 486, 228,
       535, 305, 692, 732, 657, 231, 767, 988, 940, 641, 261, 403, 452,
       766, 449, 643, 932, 151, 343, 507, 346, 702, 956, 922, 769,  76,
       245, 329, 115, 683,  19, 371, 830, 710, 725], dtype=int32)

In [13]:
def is_prime(num):
    if num<=1:
        return False
    for i in range(2,int(num**0.5)+1):
        if num % i==0:
            return False
    return True
prime_no=[]
for x in a:
    if is_prime(x):
        prime_no.append(x)
print(prime_no)
        

[np.int32(499), np.int32(23), np.int32(353), np.int32(367), np.int32(2), np.int32(401), np.int32(71), np.int32(641), np.int32(113), np.int32(641), np.int32(449), np.int32(643), np.int32(151), np.int32(769), np.int32(683), np.int32(19)]


### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages

In [38]:
daily_temperatures = np.random.uniform(20, 50, size=28)


In [39]:
daily_temperatures

array([42.92181363, 23.69637804, 21.89476515, 29.67893871, 47.25903909,
       38.0081582 , 47.0029751 , 35.82494309, 45.3561767 , 27.9869507 ,
       41.04937634, 22.09400011, 48.30445284, 25.52555733, 22.06148755,
       47.77472184, 24.35579832, 49.32410153, 32.15452656, 46.56092283,
       37.03857358, 23.41252654, 47.0619848 , 26.78443309, 35.08064121,
       20.03872031, 35.82674065, 32.11432851])

In [40]:
weekly_temperatures = daily_temperatures.reshape(4,7)


In [42]:
weekly_temperatures

array([[42.92181363, 23.69637804, 21.89476515, 29.67893871, 47.25903909,
        38.0081582 , 47.0029751 ],
       [35.82494309, 45.3561767 , 27.9869507 , 41.04937634, 22.09400011,
        48.30445284, 25.52555733],
       [22.06148755, 47.77472184, 24.35579832, 49.32410153, 32.15452656,
        46.56092283, 37.03857358],
       [23.41252654, 47.0619848 , 26.78443309, 35.08064121, 20.03872031,
        35.82674065, 32.11432851]])

In [43]:
weekly_averages = np.mean(weekly_temperatures, axis=1)

In [44]:
weekly_averages

array([35.78029542, 35.1630653 , 37.03859032, 31.47419644])